export const GET_ACTIVITIES_REQUEST = 'GET_ACTIVITIES_REQUEST'
export const GET_ACTIVITIES_SUCCESS = 'GET_ACTIVITIES_SUCCESS'
export const GET_ACTIVITIES_FAIL = 'GET_ACTIVITIES_FAIL'


export const GET_ACTIVITY_REQUEST = 'GET_ACTIVITY_REQUEST'
export const GET_ACTIVITY_SUCCESS = 'GET_ACTIVITY_SUCCESS'
export const GET_ACTIVITY_FAIL = 'GET_ACTIVITY_FAIL'


export const CREATE_ACTIVITY_REQUEST = 'CREATE_ACTIVITY_REQUEST'
export const CREATE_ACTIVITY_SUCCESS = 'CREATE_ACTIVITY_SUCCESS'
export const CREATE_ACTIVITY_FAIL = 'CREATE_ACTIVITY_FAIL'



export const DELETE_ACTIVITY_REQUEST = 'DELETE_ACTIVITY_REQUEST'
export const DELETE_ACTIVITY_SUCCESS = 'DELETE_ACTIVITY_SUCCESS'
export const DELETE_ACTIVITY_FAIL = 'DELETE_ACTIVITY_FAIL'


