export const GET_CARTITEMS_REQUEST = 'GET_CARTITEMS_REQUEST'
export const GET_CARTITEMS_SUCCESS = 'GET_CARTITEMS_SUCCESS'
export const GET_CARTITEMS_FAIL = 'GET_CARTITEMS_FAIL'



export const CREATE_CART_REQUEST = 'CREATE_CART_REQUEST'
export const CREATE_CART_SUCCESS = 'CREATE_CART_SUCCESS'
export const CREATE_CART_FAIL = 'CREATE_CART_FAIL'

export const ADD_TO_CART_REQUEST = 'ADD_TO_CART_REQUEST'
export const ADD_TO_CART_SUCCESS = 'ADD_TO_CART_SUCCESS'
export const ADD_TO_CART_FAIL = 'ADD_TO_CART_FAIL'