export const GET_DISCOVER_POSTS_REQUEST = 'GET_DISCOVER_POSTS_REQUEST'
export const GET_DISCOVER_POSTS_SUCCESS = 'GET_DISCOVER_POSTS_SUCCESS'
export const GET_DISCOVER_POSTS_FAIL = 'GET_DISCOVER_POSTS_FAIL'

export const GET_FOLLOWINGS_POSTS_REQUEST = 'GET_FOLLOWINGS_POSTS_REQUEST'
export const GET_FOLLOWINGS_POSTS_SUCCESS = 'GET_FOLLOWINGS_POSTS_SUCCESS'
export const GET_FOLLOWINGS_POSTS_FAIL = 'GET_FOLLOWINGS_POSTS_FAIL'

export const CREATE_POST_REQUEST = 'CREATE_POST_REQUEST'
export const CREATE_POST_SUCCESS = 'CREATE_POST_SUCCESS'
export const CREATE_POST_FAIL = 'CREATE_POST_FAIL'